### ISSUE TITLE
I want get mavlink.dll source code

### ISSUE THREAD

**Issue by Yofeil** [iliasam/OpenTOFLidar#16]
I use mavlink_tof.xml to generate mavlink.dll , but it is different from your mavlink.dll。
Or where should I go to get the project to your mavlink.dll。
thank you。

**Comment by iliasam** [comment]
This XML was used for generating mavlink.dll: https://github.com/iliasam/OpenTOFLidar/blob/develop/Firmware/MavlinkXML/mavlink_tof.xml
I have checked mavlink.dll files in this repository, they are actual.
I can't give you sources of mavlink.dll because they are generated dynamically by mavlink builder.  
As I can see, this DLLs contains some variable information (probably build time), so they will differ in a small part, even if they are generated from the same mavlink_tof.xml.

**Comment by iliasam** [comment]
Any questions?
