### ISSUE TITLE
measurement concern of the system

### ISSUE THREAD

**Issue by ClintSun-Git** [iliasam/OpenTOFLidar#17]
hello, you have done a great job on this project! I'm working on a sanning lidar based on polygon mirror, I have a critical question. Did you ever meet an issue that when laser rays emit to the mirror, some rays are then directly deflected to the APD lens and received by APD? In that case the distance measured is not right due to this kind of light interference. In my design, I have to use a plastic isolator to block this interference. I don't know is there such interference in your design, or the lidar system is not effected by this kind of interference due to TIA threshold, or TDC principle, etc. 
Thank you and good luck!

Kind regards,
Clint

**Comment by iliasam** [comment]
Hello.
Yes, I have seen such problem in me device.
It happened with a bigger APD lens, which was closer to the mirror comparing to the lens that is mentioned in the article and in the BOM. That problem was observed only at certain positions of the mirror (I suppose that scattering was something like this):
![image](https://user-images.githubusercontent.com/10147086/177559625-0c5b1e29-a61f-4fd2-943d-67620ea91891.png)
Maybe increasing height of the mirror can help in this case.
In my case I just stopped using bigger lens in my experiments.

Can you share information about you Lidar construction if it is possible?

**Comment by ClintSun-Git** [comment]
hello,
I upload a structure picture,
![图片](https://user-images.githubusercontent.com/78338153/177678061-bb34a694-4793-476b-ba02-f2d8781a7bc5.png)
You can also watch this teardown video of valeo ibeo used on audi, the structure is very similiar.
https://www.bilibili.com/video/BV1dL411A77G?spm_id_from=333.999.0.0&vd_source=899f9c339bd72b974a002ec80689d231. 
Did you ever make optical simulation with zemax or tracepro? It's important but very difficult.
By the way, I see MAX3658 is not good enough for your design, maybe you can try MAX3665.

**Comment by iliasam** [comment]
Thanks for the link with Audi Lidar, it was interesting.
"Did you ever make optical simulation with zemax or tracepro?"
No, firstly because I'm using commercial "off-the-shelf" lenses. I don't know exact parameters of optical elements of that lenses.

I think that it is possible to avoid interference form your first question only in optical/mechanical way - by placing isolation mechanical parts.  
Any "wrong" light (that is reflected from parts of the Lidar) will "blind" the Lidar at least to the time of laser pulse (or longer). So Lidar can't detect any close objects in that case.

Your design is rally interesting! Are you planning to make it Open Source?
How you are planning to make mirror?
As I can understand, you will need custom lenses (square shape). How you are planning to get them?

**Comment by ClintSun-Git** [comment]
Unfortunately current lidar design and product only for commercial use, did you ever think about any commercial possiblity of your design or product? I think this market still has a strong potential. 
The mirror made by ABS is covered with aluminum coating, in china we have lots of suppliers in this industry, it's convenient for this mirror and lenses. 
Are you living in Russia now? how about this market and players in your side, I know something about european and american lidar application and players, but I don't know anything about lidar in Russia.

**Comment by iliasam** [comment]
"did you ever think about any commercial possiblity of your design or product?"
I think that similar or best Lidars are already exists at the market. LD06 is an example.
Yes, I'm living in Russia now. I don't know about commercial Russian Lidars. I know that non-scanning laser rangefinders are produced here, I heard that a custom-made special Lidars are produced for special industrial devices.
I think that this is because it is to hard to compete with USA/Europe/China Lidars here.

**Comment by ClintSun-Git** [comment]
I think the advantage of LD06 is small size and cheap price, it's a very competitive product, but the technical design is poor, the parameters and performance are not clear enough or as good as they say. 
I know very less about Russia than USA/Europe, but I know Europe and the world need oil and gas from Russia, and Russia is powerful because you have very strong weapon, and everything is in a dramatic change now. I also think your hard work for open lidar is worthy of respect.

**Comment by ClintSun-Git** [comment]
hello, I'm here again and I met an issue in evaluation. I measured START and STOP signals with oscilloscope, in close distance(<30cm), when i moved the target object, the gap between these two pulses was not changed. I use hamamatsu APD and MAX3665. What's the possible reason of this issue, does it possibly caused by TIA? Thank you
![close distance 1](https://user-images.githubusercontent.com/78338153/179692186-f7a7b0f0-f52f-4bfc-acfd-dc660defafb6.jpg)
![close distance 2](https://user-images.githubusercontent.com/78338153/179692214-949ac54e-e5b9-46ae-a478-aaa273013fba.jpg)
!

**Comment by iliasam** [comment]
Hello.
"when i moved the target object, the gap between these two pulses was not changed"
What is the distance of movement?
You can write me directly to the iliasam@mail.ru
